/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMessageRecipient__factory } from "./IMessageRecipient__factory";
export { Mailbox__factory } from "./Mailbox__factory";
